spring:
  datasource:
    url: jdbc:mysql://localhost:3306/login?serverTimezone=UTC
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: G9vL!dX3y7@rWqz!kBp#NfTz*QvXeRgU1JxL0sYw!HtRuBvMzKsFtWuZoQjLrNdX
  access-exp: 3600000  # 1시간
  refresh-exp: 1209600000  # 2주